version: '3.8'

services:
  db:
    restart: always

  app:
    restart: always
    environment:
      - DATABASE_URL=postgresql://tulga:tulga_secret@db:5432/tcwallet?schema=public
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
